name: Windows Remote Access

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: self-hosted
    timeout-minutes: 360

    steps:
      - name: Get Tailscale IP
        shell: powershell
        run: |
          $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          echo "TS_IP=$ip" >> $env:GITHUB_ENV

      - name: Show Connection Info
        shell: powershell
        run: |
          Write-Host "====== RDP CONNECTION DETAILS ======"
          Write-Host "IP Address : $env:TS_IP"
          Write-Host "Username   : RDP2"
          Write-Host "Password   : Baim123"
          Write-Host "===================================="

      - name: Keep Runner Alive
        shell: powershell
        run: |
          Write-Host "Runner aktif..."
          Start-Sleep -Seconds 21600
