name: Windows Remote Access

on:
  workflow_dispatch:

jobs:
  remote-access:
    runs-on: self-hosted
    timeout-minutes: 360

    steps:
      - name: Show Connection Info
        shell: powershell
        run: |
          Write-Host "====== RDP CONNECTION DETAILS ======"
          Write-Host "IP Address : 38.253.224.14"
          Write-Host "Port       : 14117"
          Write-Host "Username   : RDP2"
          Write-Host "Password   : Baim123"
          Write-Host "===================================="

      - name: Keep Runner Alive
        shell: powershell
        run: |
          Write-Host "Runner aktif..."
          Start-Sleep -Seconds 21600
